# Generated by Django 4.2.6 on 2023-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customer_order_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='default_img.png', upload_to='products_pics'),
        ),
    ]
